package phonebook::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'phonebook::SchemaClass',

    connect_info => {
        dsn            => 'dbi:Pg:dbname=dev',
        user           => 'sapotero',
        password       => 'ijJvEn7y',
        pg_enable_utf8 => 1,
        AutoCommit => 1
    }
);


=head1 NAME

phonebook::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<phonebook>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<phonebook::SchemaClass>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

sapotero

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
